### ISSUE TITLE
Provided byte buffer insufficient capacity

### ISSUE THREAD

**Issue by davidhowe** [jwoolston/Android-Webcam#26]
Hi there,
Do you know of any workaround to the following problem?

com.jwoolston.android.uvc.demo W/System.err: java.lang.IllegalArgumentException: The provided byte buffer is of insufficient capacity. Required: 3840 Bytes. Provided: 3060 Bytes

**Comment by jwoolston** [comment]
You will have to be more specific of what you have tried and how that problem came about in order for me to help. As an aside, the implementation is still very much in development.

**Comment by madhurtewani** [comment]
Hi @jwoolston,

Even I faced this same issue and this happened on selecting MJPEGVideoFormat after connecting an HP USB HD camera.
Please find below a detailed log of the same.

```
com.jwoolston.android.uvc.demo D/StreamManager: Current error code: 0x00
com.jwoolston.android.uvc.demo W/System.err: java.lang.IllegalArgumentException: The provided byte buffer is of insufficient capacity. Required: 3840 Bytes. Provided: 3060 Bytes.
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.android.libusb.async.IsochronousAsyncTransfer.submit(IsochronousAsyncTransfer.java:47)
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.android.uvc.StreamManager.initiateStream(StreamManager.java:130)
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.android.uvc.StreamManager.establishStreaming(StreamManager.java:120)
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.android.uvc.WebcamConnection.beginConnectionStreaming(WebcamConnection.java:86)
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.android.uvc.WebcamImpl.beginStreaming(WebcamImpl.java:50)
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.usb.webcam.app.MainActivity.onNewVideoFormatSelected(MainActivity.java:91)
com.jwoolston.android.uvc.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.jwoolston.android.uvc.demo W/System.err:     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
com.jwoolston.android.uvc.demo W/System.err:     at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:434)
com.jwoolston.android.uvc.demo W/System.err:     at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
com.jwoolston.android.uvc.demo W/System.err:     at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
com.jwoolston.android.uvc.demo W/System.err:     at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
com.jwoolston.android.uvc.demo W/System.err:     at com.jwoolston.usb.webcam.app.FormatPickerDialog$2.onClick(FormatPickerDialog.java:73)
com.jwoolston.android.uvc.demo W/System.err:     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
com.jwoolston.android.uvc.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
com.jwoolston.android.uvc.demo W/System.err:     at android.os.Looper.loop(Looper.java:193)
com.jwoolston.android.uvc.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6715)
com.jwoolston.android.uvc.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.jwoolston.android.uvc.demo W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
com.jwoolston.android.uvc.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

After this nothing happened on the sample app.
Let me know if I can help you with some more details or logs that you might need.
